#!/usr/bin/env bash
# setup-agent.sh — full-stack installer (b1e55ed + OpenClaw + Telegram)
#
# Curl-pipeable:
#   curl -sSf https://raw.githubusercontent.com/P-U-C/b1e55ed/main/scripts/setup-agent.sh | bash
#
# Non-interactive:
#   ./scripts/setup-agent.sh --anthropic-key KEY --telegram-token TOKEN --preset btc
#
set -euo pipefail

# ── Colors (disable if not a TTY) ────────────────────────────────────────────
if [ -t 1 ]; then
  _B=$'\033[1m'; _D=$'\033[2m'; _G=$'\033[0;32m'; _Y=$'\033[1;33m'; _R=$'\033[0;31m'; _0=$'\033[0m'
else
  _B=""; _D=""; _G=""; _Y=""; _R=""; _0=""
fi

bold()  { printf '%s%s%s' "$_B" "$*" "$_0"; }
dim()   { printf '%s%s%s' "$_D" "$*" "$_0"; }
green() { printf '%s%s%s' "$_G" "$*" "$_0"; }
yel()   { printf '%s%s%s' "$_Y" "$*" "$_0"; }
red()   { printf '%s%s%s' "$_R" "$*" "$_0"; }

say()   { printf '%s\n' "$*"; }
ok()    { say "  $(green '✓') $*"; }
warn()  { say "  $(yel '⚠') $*"; }
fail()  { say "  $(red '✗') $*"; }

fatal() {
  say "" >&2
  fail "$*" >&2
  say "  $(dim 'Fix the issue above and re-run the script.')" >&2
  exit 1
}

need_cmd() { command -v "$1" >/dev/null 2>&1; }
step() { say ""; say "$(bold "$1")"; }
run_cmd() { say "  $(dim '→') $*"; "$@"; }

# ── Args ──────────────────────────────────────────────────────────────────────
PRESET=""
NO_SERVICE=0
WORKDIR="${B1E55ED_HOME:-$HOME/b1e55ed}"
ANTHROPIC_KEY=""
OPENAI_KEY=""
XAI_KEY=""
TELEGRAM_TOKEN=""

while [ "${1:-}" != "" ]; do
  case "$1" in
    --preset)          PRESET="${2:-}"; shift 2 ;;
    --preset=*)        PRESET="${1#*=}"; shift ;;
    --workdir)         WORKDIR="${2:-}"; shift 2 ;;
    --workdir=*)       WORKDIR="${1#*=}"; shift ;;
    --anthropic-key)   ANTHROPIC_KEY="${2:-}"; shift 2 ;;
    --anthropic-key=*) ANTHROPIC_KEY="${1#*=}"; shift ;;
    --openai-key)      OPENAI_KEY="${2:-}"; shift 2 ;;
    --openai-key=*)    OPENAI_KEY="${1#*=}"; shift ;;
    --xai-key)         XAI_KEY="${2:-}"; shift 2 ;;
    --xai-key=*)       XAI_KEY="${1#*=}"; shift ;;
    --telegram-token)  TELEGRAM_TOKEN="${2:-}"; shift 2 ;;
    --telegram-token=*) TELEGRAM_TOKEN="${1#*=}"; shift ;;
    --no-service)      NO_SERVICE=1; shift ;;
    -h|--help)
      cat <<USAGE
setup-agent.sh — full-stack setup (b1e55ed + OpenClaw + Telegram)

Options:
  --preset btc|solana|multi|degen     Symbol pack + weights
  --anthropic-key KEY                 Anthropic API key (required)
  --openai-key KEY                    OpenAI API key (optional)
  --xai-key KEY                       xAI API key (optional)
  --telegram-token TOKEN              Telegram bot token
  --no-service                        Skip service install
  --workdir PATH                      Working directory (default: \$HOME/b1e55ed)
  -h, --help                          Show help
USAGE
      exit 0 ;;
    *) fatal "Unknown argument: $1 (run with --help)" ;;
  esac
done

# ── OS detection ──────────────────────────────────────────────────────────────
OS="unknown"
case "${OSTYPE:-}" in
  darwin*) OS="macos" ;;
  linux*)  OS="linux" ;;
esac

# ── Helpers ───────────────────────────────────────────────────────────────────

ensure_workdir() { mkdir -p "$WORKDIR"; cd "$WORKDIR"; mkdir -p config data; }

install_uv_if_missing() {
  need_cmd uv && return 0
  need_cmd curl || fatal "uv is missing and curl is not available."
  warn "uv not found. Installing from https://astral.sh/uv/install.sh"
  curl -LsSf https://astral.sh/uv/install.sh | bash
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
  need_cmd uv || fatal "uv install failed. Add ~/.local/bin to PATH and re-run."
}

b1e55ed_cmd() {
  if need_cmd b1e55ed; then command -v b1e55ed
  elif [ -x "$HOME/.local/bin/b1e55ed" ]; then printf '%s' "$HOME/.local/bin/b1e55ed"
  else printf '%s' "b1e55ed"
  fi
}

openclaw_cmd() {
  if need_cmd openclaw; then command -v openclaw
  elif [ -x "/usr/local/bin/openclaw" ]; then printf '%s' "/usr/local/bin/openclaw"
  else printf '%s' "openclaw"
  fi
}

write_symbol_pack() {
  local pack="$1"
  local cfg="config/user.yaml"

  if [ ! -f "$cfg" ]; then
    warn "config/user.yaml not found — creating a minimal one."
    python3 -c "
from pathlib import Path
Path('$cfg').write_text('''# Generated by setup-agent.sh
preset: balanced
api:
  host: \"127.0.0.1\"
  port: 5050
  auth_token: \"\"
dashboard:
  host: \"127.0.0.1\"
  port: 5051
  auth_token: \"\"
universe:
  symbols: [\"BTC\",\"ETH\",\"SOL\"]
  max_size: 100
''')
"
  fi

  local symbols weights
  case "$pack" in
    btc)
      symbols='["BTC","ETH","USDT","DXY","SPY"]'
      weights='curator: 0.20\n  onchain: 0.10\n  tradfi: 0.35\n  social: 0.05\n  technical: 0.25\n  events: 0.05' ;;
    solana)
      symbols='["SOL","BONK","JUP","RAY","WIF"]'
      weights='curator: 0.20\n  onchain: 0.30\n  tradfi: 0.10\n  social: 0.20\n  technical: 0.15\n  events: 0.05' ;;
    multi)
      symbols='["BTC","ETH","SOL","SUI","HYPE"]'
      weights='curator: 0.25\n  onchain: 0.25\n  tradfi: 0.20\n  social: 0.15\n  technical: 0.10\n  events: 0.05' ;;
    degen)
      symbols='["BONK","WIF","PEPE","HYPE","SOL"]'
      weights='curator: 0.15\n  onchain: 0.25\n  tradfi: 0.10\n  social: 0.25\n  technical: 0.20\n  events: 0.05' ;;
    *) fatal "Unknown preset: $pack" ;;
  esac

  python3 -c "
from pathlib import Path
import json

cfg = Path('$cfg')
text = cfg.read_text()
lines = text.splitlines(True)

symbols = $symbols
sym_yaml = '[' + ', '.join('\"' + s + '\"' for s in symbols) + ']'
universe_block = 'universe:\n  symbols: ' + sym_yaml + '\n  max_size: 100\n'
weights_block = 'weights:\n  $weights\n'

def replace_block(src, key, new_block):
    out, i, found = [], 0, False
    while i < len(src):
        if src[i].startswith(key + ':'):
            found = True
            out.append(new_block)
            i += 1
            while i < len(src) and src[i][:1] in (' ', '\t'):
                i += 1
            continue
        out.append(src[i])
        i += 1
    if not found:
        out.append('\n' + new_block)
    return out

lines = replace_block(lines, 'universe', universe_block)
lines = replace_block(lines, 'weights', weights_block)
cfg.write_text(''.join(lines))
"
  ok "Updated config/user.yaml with symbol pack + weights."
}

write_openclaw_env() {
  local env_dir="$HOME/.openclaw"
  local env_file="$env_dir/.env"
  mkdir -p "$env_dir"
  touch "$env_file"
  chmod 600 "$env_file" 2>/dev/null || true

  python3 -c "
from pathlib import Path

env_file = Path('$env_file')
raw = env_file.read_text() if env_file.exists() else ''
kv = {}
for ln in raw.splitlines():
    ln = ln.strip()
    if ln and not ln.startswith('#') and '=' in ln:
        k, v = ln.split('=', 1)
        kv[k.strip()] = v.strip()

updates = {
  'ANTHROPIC_API_KEY': '$ANTHROPIC_KEY',
  'OPENAI_API_KEY': '$OPENAI_KEY',
  'XAI_API_KEY': '$XAI_KEY',
  'TELEGRAM_BOT_TOKEN': '$TELEGRAM_TOKEN',
}
for k, v in updates.items():
    if v:
        kv[k] = v

out = '# OpenClaw environment (generated by setup-agent.sh)\n# Keep this file secret.\n\n'
for k in ['ANTHROPIC_API_KEY','OPENAI_API_KEY','XAI_API_KEY','TELEGRAM_BOT_TOKEN']:
    if k in kv and kv[k]:
        out += f'{k}={kv[k]}\n'

env_file.write_text(out)
"
  ok "Wrote OpenClaw env: $env_file"
}

telegram_verify() {
  [ -n "$1" ] && curl -fsS "https://api.telegram.org/bot${1}/getMe" >/dev/null 2>&1
}

telegram_send_test() {
  local token="$1"
  local chat_id
  chat_id=$(curl -fsS "https://api.telegram.org/bot${token}/getUpdates" 2>/dev/null | python3 -c "
import json, sys
try:
  data = json.load(sys.stdin)
  for item in reversed(data.get('result', [])):
    m = item.get('message') or item.get('edited_message') or {}
    c = (m.get('chat') or {})
    if 'id' in c:
      print(c['id'])
      break
except Exception:
  pass
" 2>/dev/null) || true

  if [ -z "$chat_id" ]; then
    return 2
  fi

  curl -fsS -X POST "https://api.telegram.org/bot${token}/sendMessage" \
    -d "chat_id=${chat_id}" \
    --data-urlencode "text=✓ OpenClaw setup test — bot is configured." >/dev/null
  return 0
}

install_services_linux() {
  local svc_dir="$HOME/.config/systemd/user"
  mkdir -p "$svc_dir"
  local bcmd; bcmd="$(b1e55ed_cmd)"
  local ocmd; ocmd="$(openclaw_cmd)"

  cat > "$svc_dir/b1e55ed.service" << SVCEOF
[Unit]
Description=b1e55ed (API + dashboard)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$WORKDIR
ExecStart=$bcmd start --no-browser --host 127.0.0.1
Restart=on-failure
RestartSec=3
Environment=PATH=$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=default.target
SVCEOF

  cat > "$svc_dir/openclaw-gateway.service" << SVCEOF
[Unit]
Description=OpenClaw Gateway
After=network-online.target b1e55ed.service
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$HOME
ExecStart=$ocmd gateway start
Restart=on-failure
RestartSec=3
Environment=PATH=/usr/local/bin:/usr/bin:/bin:$HOME/.local/bin:$HOME/.cargo/bin
EnvironmentFile=-$HOME/.openclaw/.env

[Install]
WantedBy=default.target
SVCEOF

  ok "Wrote systemd user units: b1e55ed.service + openclaw-gateway.service"

  if need_cmd systemctl; then
    run_cmd systemctl --user daemon-reload
    run_cmd systemctl --user enable --now b1e55ed.service
    run_cmd systemctl --user enable --now openclaw-gateway.service
    systemctl --user --no-pager status b1e55ed.service 2>/dev/null || true
    systemctl --user --no-pager status openclaw-gateway.service 2>/dev/null || true
    say ""
    say "  $(dim "To keep running after logout: loginctl enable-linger $USER")"
  fi
}

install_services_macos() {
  local agents="$HOME/Library/LaunchAgents"
  mkdir -p "$agents"
  local bcmd; bcmd="$(b1e55ed_cmd)"
  local ocmd; ocmd="$(openclaw_cmd)"

  python3 -c "
from pathlib import Path
Path('$agents/com.puc.b1e55ed.plist').write_text('''<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\"><dict>
  <key>Label</key><string>com.puc.b1e55ed</string>
  <key>ProgramArguments</key><array>
    <string>$bcmd</string><string>start</string><string>--no-browser</string>
    <string>--host</string><string>127.0.0.1</string>
  </array>
  <key>WorkingDirectory</key><string>$WORKDIR</string>
  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$WORKDIR/data/b1e55ed.out.log</string>
  <key>StandardErrorPath</key><string>$WORKDIR/data/b1e55ed.err.log</string>
</dict></plist>
''')
Path('$agents/com.puc.openclaw-gateway.plist').write_text('''<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\"><dict>
  <key>Label</key><string>com.puc.openclaw-gateway</string>
  <key>ProgramArguments</key><array>
    <string>$ocmd</string><string>gateway</string><string>start</string>
  </array>
  <key>WorkingDirectory</key><string>$HOME</string>
  <key>RunAtLoad</key><true/><key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$HOME/.openclaw/gateway.out.log</string>
  <key>StandardErrorPath</key><string>$HOME/.openclaw/gateway.err.log</string>
</dict></plist>
''')
"
  ok "Wrote launchd plists for b1e55ed + openclaw-gateway"

  if need_cmd launchctl; then
    local domain="gui/$(id -u)"
    for p in com.puc.b1e55ed com.puc.openclaw-gateway; do
      launchctl bootout "$domain" "$agents/$p.plist" 2>/dev/null || true
      launchctl bootstrap "$domain" "$agents/$p.plist" 2>/dev/null || launchctl load -w "$agents/$p.plist" 2>/dev/null || true
    done
    ok "launchd jobs loaded."
  fi
}

# ═════════════════════════════════════════════════════════════════════════════
# MAIN
# ═════════════════════════════════════════════════════════════════════════════

say ""
say "  ╔══════════════════════════════════════════╗"
say "  ║$(bold '   b1e55ed + OpenClaw agent setup   ')║"
say "  ║$(dim  '  AI operator + Telegram alerts     ')║"
say "  ╚══════════════════════════════════════════╝"
say ""

ensure_workdir

# ── [1/6] Prerequisites ──────────────────────────────────────────────────────
step "[1/6] Prerequisites"
say "  $(dim 'Checking: git, curl, Python 3.11+, uv, Node.js')"

need_cmd git  || fatal "git is required."
need_cmd curl || fatal "curl is required."

install_uv_if_missing
ok "uv: $(uv --version 2>/dev/null | head -1)"

if need_cmd node && need_cmd npm; then
  ok "Node.js: $(node --version 2>/dev/null)"
else
  warn "Node.js not found."
  say "  $(dim 'OpenClaw requires Node.js 20+. Ubuntu example:')"
  say "    $(dim 'curl -fsSL https://deb.nodesource.com/setup_22.x | sudo -E bash -')"
  say "    $(dim 'sudo apt-get install -y nodejs')"
fi

# ── [2/6] Install b1e55ed ────────────────────────────────────────────────────
step "[2/6] Install b1e55ed"
say "  $(dim 'Running the official installer (idempotent).')"

bash -c 'curl -sSf https://raw.githubusercontent.com/P-U-C/b1e55ed/main/install.sh | bash'
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

BCMD="$(b1e55ed_cmd)"
"$BCMD" --version >/dev/null 2>&1 || fatal "b1e55ed --version failed."
ok "b1e55ed: $("$BCMD" --version 2>/dev/null | head -1)"

# Run wizard
say "  $(dim 'Running b1e55ed wizard (identity + config)...')"
( cd "$WORKDIR" && "$BCMD" wizard ) || fatal "Wizard failed. Retry: cd $WORKDIR && b1e55ed wizard"

# Apply preset if given
if [ -n "$PRESET" ]; then
  write_symbol_pack "$PRESET"
fi

# ── [3/6] Install OpenClaw ───────────────────────────────────────────────────
step "[3/6] Install OpenClaw"

if ! need_cmd npm; then
  warn "npm not found — skipping OpenClaw install."
  say "  $(dim 'Install Node.js + npm, then re-run this script.')"
else
  say "  $(dim 'Installing: npm install -g openclaw')"
  run_cmd npm install -g openclaw
  OCMD="$(openclaw_cmd)"
  "$OCMD" --version >/dev/null 2>&1 || fatal "openclaw --version failed."
  ok "OpenClaw: $("$OCMD" --version 2>/dev/null | head -1)"
fi

# ── [4/6] Configure API keys ─────────────────────────────────────────────────
step "[4/6] Configure OpenClaw API keys"
say "  $(dim 'Keys are stored in ~/.openclaw/.env (used by the gateway).')"

if [ -z "$ANTHROPIC_KEY" ] && [ -t 0 ]; then
  say ""
  say "  Anthropic API key $(bold '(required)')"
  say "  $(dim 'Get one at: https://console.anthropic.com/')"
  read -r -p "  Key: " ANTHROPIC_KEY 2>/dev/null || true
fi
[ -n "$ANTHROPIC_KEY" ] || fatal "Anthropic API key is required. Re-run with --anthropic-key KEY"
ok "Anthropic key set"

if [ -z "$OPENAI_KEY" ] && [ -t 0 ]; then
  say ""
  say "  OpenAI API key $(dim '(optional, for Codex tasks)')"
  read -r -p "  Key [skip]: " OPENAI_KEY 2>/dev/null || true
fi

if [ -z "$XAI_KEY" ] && [ -t 0 ]; then
  say ""
  say "  xAI API key $(dim '(optional, for Twitter intel)')"
  read -r -p "  Key [skip]: " XAI_KEY 2>/dev/null || true
fi

# ── [5/6] Connect Telegram ───────────────────────────────────────────────────
step "[5/6] Connect Telegram"
say "  $(dim 'Create a bot via @BotFather in Telegram:')"
say "  $(dim '  1. Open @BotFather → /newbot')"
say "  $(dim '  2. Pick a name and username')"
say "  $(dim '  3. Copy the bot token BotFather gives you')"

if [ -z "$TELEGRAM_TOKEN" ] && [ -t 0 ]; then
  say ""
  read -r -p "  Bot token: " TELEGRAM_TOKEN 2>/dev/null || true
fi
[ -n "$TELEGRAM_TOKEN" ] || fatal "Telegram token is required. Re-run with --telegram-token TOKEN"

if telegram_verify "$TELEGRAM_TOKEN"; then
  ok "Token valid (getMe OK)"
else
  fatal "Telegram token verification failed. Double-check and retry."
fi

# Write all keys
write_openclaw_env

# Configure OpenClaw telegram token via CLI
if need_cmd openclaw; then
  OCMD="$(openclaw_cmd)"
  "$OCMD" config set telegram.token "$TELEGRAM_TOKEN" 2>/dev/null || true
  ok "Telegram token written to OpenClaw config"
fi

# Test message
if [ -t 0 ]; then
  say ""
  say "  $(dim 'To test: open your bot in Telegram, tap Start (or send /start),')"
  say "  $(dim 'then press Enter here to send a test message.')"
  read -r -p "  Press Enter when ready... " _ 2>/dev/null || true

  if telegram_send_test "$TELEGRAM_TOKEN"; then
    ok "Test message sent via Telegram!"
  else
    warn "Could not send test message (no chat found yet)."
    say "  $(dim 'Fix: message the bot first, then re-run or test manually.')"
  fi
fi

# ── [6/6] Start services ─────────────────────────────────────────────────────
step "[6/6] Start services"

if [ "$NO_SERVICE" -eq 1 ]; then
  say "  $(dim '--no-service set; skipping.')"
else
  case "$OS" in
    linux) install_services_linux ;;
    macos) install_services_macos ;;
    *)     warn "Unknown OS; cannot install services automatically." ;;
  esac
fi

# ── Summary ───────────────────────────────────────────────────────────────────
say ""
say "$(bold 'Summary')"
say "  Workdir:      $WORKDIR"
say "  b1e55ed API:  http://127.0.0.1:5050/api/v1/health"
say "  Dashboard:    http://127.0.0.1:5051"
say "  OpenClaw:     openclaw gateway status"

# Get bot username
if [ -n "$TELEGRAM_TOKEN" ]; then
  BOT_USER=$(curl -fsS "https://api.telegram.org/bot${TELEGRAM_TOKEN}/getMe" 2>/dev/null | python3 -c "
import json,sys
try:
  d=json.load(sys.stdin)
  print((d.get('result') or {}).get('username',''))
except Exception: pass
" 2>/dev/null) || true
  if [ -n "${BOT_USER:-}" ]; then
    say "  Telegram:     https://t.me/${BOT_USER}"
  fi
fi

say ""
say "$(bold 'Next steps:')"
say "  1. Open Telegram and message your bot."
say "  2. Tail logs:"
if [ "$OS" = "linux" ]; then
  say "     journalctl --user -u b1e55ed -f"
  say "     journalctl --user -u openclaw-gateway -f"
else
  say "     tail -f $WORKDIR/data/b1e55ed.out.log"
  say "     tail -f $HOME/.openclaw/gateway.out.log"
fi
say ""
