#!/usr/bin/env bash
# setup-standalone.sh — interactive standalone installer for b1e55ed
#
# Curl-pipeable:
#   curl -sSf https://raw.githubusercontent.com/P-U-C/b1e55ed/main/scripts/setup-standalone.sh | bash
#
# Non-interactive (CI/automation):
#   ./scripts/setup-standalone.sh --preset btc --no-service
#
set -euo pipefail

# ── Colors (disable if not a TTY) ────────────────────────────────────────────
if [ -t 1 ]; then
  _B=$'\033[1m'; _D=$'\033[2m'; _G=$'\033[0;32m'; _Y=$'\033[1;33m'; _R=$'\033[0;31m'; _0=$'\033[0m'
else
  _B=""; _D=""; _G=""; _Y=""; _R=""; _0=""
fi

bold()  { printf '%s%s%s' "$_B" "$*" "$_0"; }
dim()   { printf '%s%s%s' "$_D" "$*" "$_0"; }
green() { printf '%s%s%s' "$_G" "$*" "$_0"; }
yel()   { printf '%s%s%s' "$_Y" "$*" "$_0"; }
red()   { printf '%s%s%s' "$_R" "$*" "$_0"; }

say()   { printf '%s\n' "$*"; }
ok()    { say "  $(green '✓') $*"; }
warn()  { say "  $(yel '⚠') $*"; }
fail()  { say "  $(red '✗') $*"; }

fatal() {
  say "" >&2
  fail "$*" >&2
  say "  $(dim 'Fix the issue above and re-run the script.')" >&2
  exit 1
}

need_cmd() { command -v "$1" >/dev/null 2>&1; }

step() { say ""; say "$(bold "$1")"; }

run_cmd() { say "  $(dim '→') $*"; "$@"; }

# ── Args ──────────────────────────────────────────────────────────────────────
PRESET=""
NO_SERVICE=0
WORKDIR="${B1E55ED_HOME:-$HOME/b1e55ed}"

while [ "${1:-}" != "" ]; do
  case "$1" in
    --preset)     PRESET="${2:-}"; shift 2 ;;
    --preset=*)   PRESET="${1#*=}"; shift ;;
    --no-service) NO_SERVICE=1; shift ;;
    --workdir)    WORKDIR="${2:-}"; shift 2 ;;
    --workdir=*)  WORKDIR="${1#*=}"; shift ;;
    -h|--help)
      cat <<USAGE
setup-standalone.sh — b1e55ed standalone setup wizard

Options:
  --preset btc|solana|multi|degen   Symbol pack + weights (non-interactive)
  --no-service                      Skip background service install
  --workdir PATH                    Working directory (default: \$HOME/b1e55ed)
  -h, --help                        Show help
USAGE
      exit 0 ;;
    *) fatal "Unknown argument: $1 (run with --help)" ;;
  esac
done

# ── OS detection ──────────────────────────────────────────────────────────────
OS="unknown"
case "${OSTYPE:-}" in
  darwin*) OS="macos" ;;
  linux*)  OS="linux" ;;
esac

# ── Helper functions ──────────────────────────────────────────────────────────

ensure_workdir() { mkdir -p "$WORKDIR"; cd "$WORKDIR"; mkdir -p config data; }

check_python_311() {
  local py
  for py in python3.13 python3.12 python3.11 python3; do
    if need_cmd "$py"; then
      local ver; ver="$("$py" -c 'import sys; print(f"{sys.version_info.major}.{sys.version_info.minor}")' 2>/dev/null)" || continue
      local major; major="${ver%%.*}"
      local minor; minor="${ver##*.}"
      if [ "$major" -ge 3 ] && [ "$minor" -ge 11 ]; then
        printf '%s' "$py"
        return 0
      fi
    fi
  done
  return 1
}

install_uv_if_missing() {
  need_cmd uv && return 0
  need_cmd curl || fatal "uv is missing and curl is not available. Install curl, then re-run."
  warn "uv not found."
  say "  $(dim 'Why: b1e55ed uses uv for reproducible Python environments.')"
  say "  $(dim 'Installing from https://astral.sh/uv/install.sh')"
  curl -LsSf https://astral.sh/uv/install.sh | bash
  export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"
  need_cmd uv || fatal "uv install did not put 'uv' on PATH. Add ~/.local/bin to PATH and re-run."
}

b1e55ed_cmd() {
  if need_cmd b1e55ed; then command -v b1e55ed
  elif [ -x "$HOME/.local/bin/b1e55ed" ]; then printf '%s' "$HOME/.local/bin/b1e55ed"
  else printf '%s' "b1e55ed"
  fi
}

choose_pack_interactive() {
  say ""
  say "  Choose a symbol pack:"
  say ""
  say "  $(bold '1)') BTC Core         — BTC, ETH, USDT, DXY, SPY"
  say "  $(bold '2)') Solana Ecosystem  — SOL, BONK, JUP, RAY, WIF"
  say "  $(bold '3)') Multi-Asset       — BTC, ETH, SOL, SUI, HYPE"
  say "  $(bold '4)') Multi-Asset Degen — BONK, WIF, PEPE, HYPE, SOL"
  say "  $(bold '5)') Custom            — enter your own"
  say ""

  local choice
  read -r -p "  Pack [1]: " choice 2>/dev/null || choice="1"
  choice="${choice:-1}"

  case "$choice" in
    1) PRESET="btc" ;;
    2) PRESET="solana" ;;
    3) PRESET="multi" ;;
    4) PRESET="degen" ;;
    5) PRESET="custom" ;;
    *) PRESET="btc" ;;
  esac
}

write_symbol_pack() {
  local pack="$1"
  local cfg="config/user.yaml"

  # Create minimal config if it doesn't exist yet
  if [ ! -f "$cfg" ]; then
    warn "config/user.yaml not found — creating a minimal one."
    python3 -c "
from pathlib import Path
Path('$cfg').write_text('''# Generated by setup-standalone.sh
preset: balanced

api:
  host: \"127.0.0.1\"
  port: 5050
  auth_token: \"\"

dashboard:
  host: \"127.0.0.1\"
  port: 5051
  auth_token: \"\"

universe:
  symbols: [\"BTC\",\"ETH\",\"SOL\"]
  max_size: 100
''')
"
  fi

  # Symbol packs: symbols_json + weights YAML block
  local symbols weights
  case "$pack" in
    btc)
      symbols='["BTC","ETH","USDT","DXY","SPY"]'
      weights='curator: 0.20\n  onchain: 0.10\n  tradfi: 0.35\n  social: 0.05\n  technical: 0.25\n  events: 0.05' ;;
    solana)
      symbols='["SOL","BONK","JUP","RAY","WIF"]'
      weights='curator: 0.20\n  onchain: 0.30\n  tradfi: 0.10\n  social: 0.20\n  technical: 0.15\n  events: 0.05' ;;
    multi)
      symbols='["BTC","ETH","SOL","SUI","HYPE"]'
      weights='curator: 0.25\n  onchain: 0.25\n  tradfi: 0.20\n  social: 0.15\n  technical: 0.10\n  events: 0.05' ;;
    degen)
      symbols='["BONK","WIF","PEPE","HYPE","SOL"]'
      weights='curator: 0.15\n  onchain: 0.25\n  tradfi: 0.10\n  social: 0.25\n  technical: 0.20\n  events: 0.05' ;;
    custom)
      say ""
      say "  Enter symbols as a comma-separated list (example: BTC,ETH,SOL)"
      local raw; read -r -p "  Symbols: " raw 2>/dev/null || raw="BTC,ETH,SOL"
      raw="${raw:-BTC,ETH,SOL}"
      symbols=$(python3 -c "
import json
s='$raw'
syms=[x.strip().upper() for x in s.split(',') if x.strip()] or ['BTC','ETH','SOL']
print(json.dumps(syms))
")
      weights='curator: 0.25\n  onchain: 0.25\n  tradfi: 0.20\n  social: 0.15\n  technical: 0.10\n  events: 0.05' ;;
    *) fatal "Unknown preset: $pack" ;;
  esac

  python3 -c "
from pathlib import Path
import json

cfg = Path('$cfg')
text = cfg.read_text()
lines = text.splitlines(True)

symbols = $symbols
sym_yaml = '[' + ', '.join(f'\"' + s + '\"' for s in symbols) + ']'
universe_block = 'universe:\n  symbols: ' + sym_yaml + '\n  max_size: 100\n'
weights_block = 'weights:\n  $weights\n'

def replace_block(src, key, new_block):
    out, i, found = [], 0, False
    while i < len(src):
        if src[i].startswith(key + ':'):
            found = True
            out.append(new_block)
            i += 1
            while i < len(src) and src[i][:1] in (' ', '\t'):
                i += 1
            continue
        out.append(src[i])
        i += 1
    if not found:
        out.append('\n' + new_block)
    return out

lines = replace_block(lines, 'universe', universe_block)
lines = replace_block(lines, 'weights', weights_block)
cfg.write_text(''.join(lines))
"

  ok "Updated $(bold "$cfg") with symbol pack + weights."
}

install_service_linux() {
  local svc_dir="$HOME/.config/systemd/user"
  mkdir -p "$svc_dir"
  local bcmd; bcmd="$(b1e55ed_cmd)"

  cat > "$svc_dir/b1e55ed.service" << SVCEOF
[Unit]
Description=b1e55ed (API + dashboard)
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
WorkingDirectory=$WORKDIR
ExecStart=$bcmd start --no-browser --host 127.0.0.1
Restart=on-failure
RestartSec=3
Environment=PATH=$HOME/.local/bin:$HOME/.cargo/bin:/usr/local/bin:/usr/bin:/bin

[Install]
WantedBy=default.target
SVCEOF

  ok "Wrote systemd user unit: $svc_dir/b1e55ed.service"

  if need_cmd systemctl; then
    run_cmd systemctl --user daemon-reload
    run_cmd systemctl --user enable --now b1e55ed.service
    systemctl --user --no-pager status b1e55ed.service 2>/dev/null || true
    say ""
    say "  $(dim 'To keep it running after logout:')"
    say "    $(dim "loginctl enable-linger $USER")"
  else
    warn "systemctl not found. Run manually: cd $WORKDIR && b1e55ed start --no-browser"
  fi
}

install_service_macos() {
  local plist="$HOME/Library/LaunchAgents/com.puc.b1e55ed.plist"
  mkdir -p "$HOME/Library/LaunchAgents"
  local bcmd; bcmd="$(b1e55ed_cmd)"

  python3 -c "
from pathlib import Path
Path('$plist').write_text('''<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
  <key>Label</key><string>com.puc.b1e55ed</string>
  <key>ProgramArguments</key>
  <array>
    <string>$bcmd</string>
    <string>start</string>
    <string>--no-browser</string>
    <string>--host</string>
    <string>127.0.0.1</string>
  </array>
  <key>WorkingDirectory</key><string>$WORKDIR</string>
  <key>RunAtLoad</key><true/>
  <key>KeepAlive</key><true/>
  <key>StandardOutPath</key><string>$WORKDIR/data/b1e55ed.out.log</string>
  <key>StandardErrorPath</key><string>$WORKDIR/data/b1e55ed.err.log</string>
</dict>
</plist>
''')
"

  ok "Wrote launchd plist: $plist"

  if need_cmd launchctl; then
    local domain="gui/$(id -u)"
    launchctl bootout "$domain" "$plist" 2>/dev/null || true
    run_cmd launchctl bootstrap "$domain" "$plist" 2>/dev/null || launchctl load -w "$plist" 2>/dev/null || true
    ok "launchd job loaded."
  fi
}

# ═════════════════════════════════════════════════════════════════════════════
# MAIN
# ═════════════════════════════════════════════════════════════════════════════

say ""
say "  ╔══════════════════════════════════════════╗"
say "  ║$(bold '      b1e55ed standalone setup      ')║"
say "  ║$(dim  '  contributor intelligence engine   ')║"
say "  ╚══════════════════════════════════════════╝"
say ""

ensure_workdir

# ── [1/5] Prerequisites ──────────────────────────────────────────────────────
step "[1/5] Check prerequisites"
say "  $(dim 'Checking: uv, Python 3.11+, git')"

if PY_BIN="$(check_python_311)"; then
  ok "Python: $PY_BIN"
else
  warn "Python 3.11+ not found. install.sh can bootstrap it via uv."
fi

need_cmd git || fatal "git is required. Install: Ubuntu: sudo apt install git; macOS: xcode-select --install"
ok "git found"

install_uv_if_missing
ok "uv: $(uv --version 2>/dev/null | head -1)"

# ── [2/5] Install b1e55ed ────────────────────────────────────────────────────
step "[2/5] Install b1e55ed"
say "  $(dim 'Running the official installer (idempotent).')"
need_cmd curl || fatal "curl is required."

bash -c 'curl -sSf https://raw.githubusercontent.com/P-U-C/b1e55ed/main/install.sh | bash'
export PATH="$HOME/.local/bin:$HOME/.cargo/bin:$PATH"

BCMD="$(b1e55ed_cmd)"
"$BCMD" --version >/dev/null 2>&1 || fatal "b1e55ed --version failed. Check install output above."
ok "b1e55ed installed: $("$BCMD" --version 2>/dev/null | head -1)"

# ── [3/5] Run wizard ─────────────────────────────────────────────────────────
step "[3/5] Run b1e55ed wizard"
say "  $(dim 'The wizard handles identity forge + initial config.')"
say "  $(dim "Working directory: $WORKDIR")"

( cd "$WORKDIR" && "$BCMD" wizard ) || fatal "Wizard failed. Retry: cd $WORKDIR && b1e55ed wizard"

# ── [4/5] Symbol pack ────────────────────────────────────────────────────────
step "[4/5] Choose symbol pack"

if [ -n "$PRESET" ]; then
  say "  $(dim "Non-interactive preset: $PRESET")"
else
  choose_pack_interactive
fi

case "$PRESET" in
  btc|solana|multi|degen|custom) : ;;
  "") PRESET="btc" ;;
  *) fatal "Invalid --preset '$PRESET' (expected btc|solana|multi|degen)" ;;
esac

write_symbol_pack "$PRESET"

# ── [5/5] Service ────────────────────────────────────────────────────────────
step "[5/5] Start as service?"
START_SVC=1

if [ "$NO_SERVICE" -eq 1 ]; then
  START_SVC=0
  say "  $(dim '--no-service set; skipping.')"
elif [ -t 0 ]; then
  read -r -p "  Install + start service now? [Y/n]: " yn 2>/dev/null || yn="Y"
  yn="${yn:-Y}"
  case "$yn" in n|N|no|NO) START_SVC=0 ;; esac
fi

if [ "$START_SVC" -eq 1 ]; then
  case "$OS" in
    linux) install_service_linux ;;
    macos) install_service_macos ;;
    *)     warn "Unknown OS; cannot install service automatically."; START_SVC=0 ;;
  esac
fi

# ── Summary ───────────────────────────────────────────────────────────────────
say ""
say "$(bold 'Summary')"
say "  Workdir:   $WORKDIR"
say "  Config:    $WORKDIR/config/user.yaml"
say "  API:       http://127.0.0.1:5050/api/v1/health"
say "  Dashboard: http://127.0.0.1:5051"

if [ "$START_SVC" -eq 1 ]; then
  case "$OS" in
    linux) say "  Service:   systemd user unit 'b1e55ed.service'" ;;
    macos) say "  Service:   launchd job 'com.puc.b1e55ed'" ;;
  esac
else
  say "  Service:   not installed"
  say "  $(dim "Next: cd \"$WORKDIR\" && b1e55ed start --no-browser")"
fi
say ""
